name: Check for New Commits

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new commits
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.APP_URL }}/api/check-commits
